version: "3.8"

services:
  database:
    image: mongo:7.0   # Official Mongo image
    container_name: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    restart: always
    networks:
      - backend-network
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: >
        mongosh --username ${MONGO_INITDB_ROOT_USERNAME} --password ${MONGO_INITDB_ROOT_PASSWORD} --authenticationDatabase admin --eval "db.adminCommand('ping')"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build: ./backend
    container_name: api
    restart: always
    depends_on:
      database:
        condition: service_healthy
    networks:
      - backend-network
      - frontend-network
    environment:
      MONGO_URI: ${MONGO_URI}
      BACKEND_PORT: ${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"

  frontend:
    build: ./frontend
    container_name: ui
    restart: always
    depends_on:
      - backend
    networks:
      - frontend-network
    ports:
      - "80:80"
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}

networks:
  backend-network:
  frontend-network:

volumes:
  mongo-data: